spring.application.name=DevopsTask-2
spring.datasource.url = jdbc:mysql://localhost:3306/workers_database
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto= update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
